default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: sm_lab_development

test:
  <<: *default
  database: sm_lab_test

production:
  <<: *default
  database: sm_lab_production
  username: sm_lab
  password: <%= ENV['sm_lab_DATABASE_PASSWORD'] %>
